### ISSUE TITLE
Rolling chart does not plot zeros.

### ISSUE THREAD

**Issue by MatthijsReyers** [utwente-db/eca#2]
When plotting a continuous stream of integers the rolling chart will not chart zeros and instead place a gap whenever an attempt to do so is made.

This is clearly caused by line 74 in /lib/charts.js
```js
data[k].push(message.values[k] || null);
```

I have a local branch with bug fix ready, but I was just wondering if this is maybe intended behaviour?
If not I could create I pull request.

**Comment by mvankeulen** [comment]
There are situations where you would like to display graphs with gaps, but being able to display zeros is desirable as well. So, my question is, is it possible in your bug fix to display a disrupted graph in some way?

Kind regards,
Maurice

**Comment by MatthijsReyers** [comment]
Hi Maurice, in the my version you can still plot a disrupted graph by simply providing the python null type: `None` as value.

**Comment by mvankeulen** [comment]
The please make a pull request. And thanks for solving the bug.

Kind regards,
Maurice
